/**
 * Base abstract class defining the interface for all AI model providers.
 * All concrete providers (e.g. GroqProvider) must extend this class.
 */
class BaseProvider {
  /**
   * Generates a raw text response from a prompt.
   * @param {string} prompt - User prompt
   * @param {string} [systemInstruction] - Optional system instruction/persona rules
   * @returns {Promise<string>} Text generated by the model
   */
  async generateResponse(prompt, systemInstruction = '') {
    throw new Error('Method generateResponse() must be implemented');
  }

  /**
   * Generates a validated structured JSON object matching a given schema.
   * @param {string} prompt - User prompt
   * @param {object} schema - Expected JSON schema structure
   * @param {string} [systemInstruction] - Optional system instruction
   * @returns {Promise<object>} JSON object generated by the model
   */
  async generateStructuredResponse(prompt, schema, systemInstruction = '') {
    throw new Error('Method generateStructuredResponse() must be implemented');
  }

  /**
   * Executes a conversation cycle supporting function calling / tool execution.
   * @param {string} userMessage - New incoming user query
   * @param {Array<object>} [chatHistory] - List of previous chat history logs
   * @param {Array<object>} [tools] - List of tool schemas available to the model
   * @param {string} userId - Authenticated user identifier for transaction bounds
   * @returns {Promise<object>} Chat outcome (containing text response or details about tool requests)
   */
  async executeWithTools(userMessage, chatHistory = [], tools = [], userId) {
    throw new Error('Method executeWithTools() must be implemented');
  }

  /**
   * Standardized error handling routine for AI operations.
   * @param {Error} error - Raw exception caught
   * @throws {Error} Wraps and prints standard exception logs
   */
  handleError(error) {
    console.error(`[AI Provider Exception]: ${error.stack || error.message}`);
    throw new Error(`AI Provider Operation Failed: ${error.message}`);
  }
}

module.exports = BaseProvider;
